#!/bin/bash
# =========================================================
# Taskfile gives you a set of quick tasks for your project
# More info: https://github.com/Enrise/Taskfile
# =========================================================

function banner {
	echo -e "${BLUE}\n"\
	"████████╗ █████╗ ███████╗██╗  ██╗███████╗██╗██╗     ███████╗\n"\
	"╚══██╔══╝██╔══██╗██╔════╝██║ ██╔╝██╔════╝██║██║     ██╔════╝\n"\
	"   ██║   ███████║███████╗█████╔╝ █████╗  ██║██║     █████╗  \n"\
	"   ██║   ██╔══██║╚════██║██╔═██╗ ██╔══╝  ██║██║     ██╔══╝  \n"\
	"   ██║   ██║  ██║███████║██║  ██╗██║     ██║███████╗███████╗\n"\
	"   ╚═╝   ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝     ╚═╝╚══════╝╚══════╝${RESET}"
}

# =========================================================
## Project
# =========================================================

function task:init { ## Set up the project for local development
	project:git-config
	task:update
	task:help
}

function task:update { ## Update all project dependencies
	project:install-dependencies
}

function task:pr { ## Check out pull request <number> and update
	project:checkout-pr $1
	task:update
}

function project:checkout-pr {
	title "Checking out pull request"
	if [ -z "$1" ]
	then
		echo "You need to provide a pull request number to check out."
		echo -e "${BLUE}Usage:${RESET} $0 pr ${YELLOW}<number>${RESET}"
		exit 1
	fi
	echo "Checking out pull request $1..."
	git fetch origin refs/pull/$1/head:refs/remotes/origin/pr/$1
	git checkout origin/pr/$1
}

function project:install-dependencies {
	title "Installing dependencies"
	npm install
}

function project:git-config {
	title "Setting git configuration"
	git config --local core.hooksPath dev/git-hooks
	echo -e "Git hooks directory is set to ${YELLOW}./dev/git-hooks${RESET}."
}

# =========================================================
## Development
# =========================================================

function task:start { ## Start development mode
	title "Run project in development mode"
	npm run dev
}

function task:production { ## Build and run production output
	title "Build production application"
	npm run build
	title "Run production container"
	echo -e "Production:    ${BLUE}http://localhost:3089${RESET}\n"
	docker run --rm --publish 3089:80 --name tasksite --volume ./out:/var/www nstapelbroek/static-webserver:5
}

function task:prettier { ## Prettify all files
	title "Running prettier"
	echo "Prettifying files..."
	prettier --config dev/linting/.prettierrc.json --ignore-path dev/linting/.prettierignore --write --list-different . \
		&& echo -e "All ${GREEN}good${RESET}."
}

function task:eslint { ## Check typescript logic
	title "ESLint"
	echo "Checking typescript logic..."
	eslint --config dev/linting/eslint.config.mjs . \
		&& echo -e "All ${GREEN}good${RESET}."
}

function task:typescript { ## Check typescript types
	title "Typescript type check"
	echo "Checking typescript types..."
	tsc --noEmit --project . --pretty \
		&& echo -e "All ${GREEN}good${RESET}."
}

# =========================================================
## Automation
# =========================================================

function task:pre-commit { ## Clean up code before committing
	task:eslint
	task:prettier
	task:typescript
	title "Committing"
}

# =========================================================
## Taskfile
# =========================================================

set -eo pipefail

BLUE=$(printf '\033[36m')
YELLOW=$(printf '\033[33m')
RED=$(printf '\033[31m')
GREEN=$(printf '\033[32m')
RESET=$(printf '\033[0m')

PATH=./node_modules/.bin:$PATH

function title {
	echo -e "\n${BLUE}=>${RESET} $1\n"
}

function task:help { ## Show all available tasks
	banner
	title "Available tasks"
	awk 'BEGIN {FS = " { [#][#][ ]?"} /^([a-zA-Z_-]*:?.*)(\{ )?[#][#][ ]?/ \
		{printf "\033[33m%-34s\033[0m %s\n", $1, $2}' $0 |\
		sed -E "s/[#]{2,}[ ]*/${RESET}/g" |\
		sed -E "s/function task:*/  /g"
	echo -e "\n${BLUE}Usage:${RESET} ./Taskfile ${YELLOW}<task>${RESET} <args>"
}

function task:shorthand { ## Create CLI shorthand task instead of ./Taskfile
	title "Creating task shorthand"
	echo -e "You're about to create ${YELLOW}/usr/local/bin/task${RESET} that requires ${RED}root${RESET} permission..."
	sudo curl --location --silent --output /usr/local/bin/task https://enri.se/taskfile-bin
	sudo chmod +x /usr/local/bin/task
	echo -e "${BLUE}You can now use:${RESET} task ${YELLOW}<task>${RESET} <arguments>"
}

if [[ ! "$(declare -F task:${@-help})" ]]; then
	title "Task not found"
	echo -e "Task ${YELLOW}$1${RESET} doesn't exist."
	task:help
	exit 1
fi
task:${@-help}
